//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

// Package common contains common properties used by the subpackages.
package common ;import _bf "time";const _ad =2;const _f ="\u0032\u0020\u004aan\u0075\u0061\u0072\u0079\u0020\u0032\u0030\u0030\u0036\u0020\u0061\u0074\u0020\u0031\u0035\u003a\u0030\u0034";var ReleasedAt =_bf .Date (_a ,_ad ,_ag ,_af ,_d ,0,0,_bf .UTC );
const _ag =16;const _a =2026;const _d =20;const _af =12;const Version ="\u0030\u002e\u0031\u0035\u002e\u0030";

// UtcTimeFormat returns a formatted string describing a UTC timestamp.
func UtcTimeFormat (t _bf .Time )string {return t .Format (_f )+"\u0020\u0055\u0054\u0043"};